language: java
jdk:
- oraclejdk9
script: mvn install -f Java9ModuleSystem

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/Java9-module-system-with-maven

