language: java
jdk:
- oraclejdk9
script: mvn install -f Java9ModuleSystem
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/Java9-module-system-with-maven

before_install:
    - set -eo pipefail
    - wget http://www-us.apache.org/dist//ant/binaries/apache-ant-1.10.1-bin.tar.gz;
    - tar -xzf apache-ant-1.10.1-bin.tar.gz;
    - PATH=apache-ant-1.10.1/bin:$PATH;

